# Some services are added by default by Fork (so you don't need to add them here manually) :
# - Router
#
# Here you can add additional services that you need
# Just give the class and namespace of your service : Name\Space\To\Your\Class::class
# Your service need to have a basic constructor without params : __construct()
services:
